version: '3'

services:
  web:
    #stdin_open: true
    working_dir: /app
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:80"
    volumes:
      - /app/node_modules
      - .:/app
  
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
